// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func App() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script defer src=\"https://unpkg.com/htmx.org@2.0.2\" integrity=\"sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ\" crossorigin=\"anonymous\"></script><script defer src=\"https://unpkg.com/htmx-ext-multi-swap@2.0.0/multi-swap.js\"></script><script defer src=\"https://unpkg.com/htmx-ext-json-enc@2.0.1/json-enc.js\"></script></head><body><form class=\"w-full flex flex-col gap-4\" hx-encoding=\"multipart/form-data\" hx-post=\"/button\" hx-target=\"body\" hx-swap=\"outerHTML\"><button type=\"submit\">Click me</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SetupListeners().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func SetupListeners() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_SetupListeners_68b9`,
		Function: `function __templ_SetupListeners_68b9(){document.body.addEventListener("htmx:beforeRequest", function(event) {
    console.log("htmx:beforeRequest", event);
    const button = document.querySelector("button")
    button.disabled = true
    button.textContent = "Loading..."
  });

  document.body.addEventListener("htmx:afterRequest", function(event) {
    console.log("htmx:afterRequest", event);
    const button = document.querySelector("button")
    button.disabled = false
    button.textContent = "Click me"
  });

  document.body.addEventListener("htmx:responseError", function(event) {
    console.log("htmx:responseError", event);
    const buttons = document.querySelector("button")
    const button = document.querySelector("button")
    button.disabled = false
    button.textContent = "Click me"
  });
}`,
		Call:       templ.SafeScript(`__templ_SetupListeners_68b9`),
		CallInline: templ.SafeScriptInline(`__templ_SetupListeners_68b9`),
	}
}
